# GoReleaser configuration for cache-cleaner
# Documentation: https://goreleaser.com

version: 2

before:
  hooks:
    # Run go mod tidy in each app directory
    - sh -c "cd dev-cache && go mod tidy"
    - sh -c "cd git-cleaner && go mod tidy"
    - sh -c "cd mac-cache-cleaner && go mod tidy"

builds:
  # dev-cache binary
  - id: dev-cache
    main: ./main.go
    dir: ./dev-cache
    binary: dev-cache
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

  # git-cleaner binary
  - id: git-cleaner
    main: ./main.go
    dir: ./git-cleaner
    binary: git-cleaner
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

  # mac-cache-cleaner binary
  - id: mac-cache-cleaner
    main: ./main.go
    dir: ./mac-cache-cleaner
    binary: mac-cache-cleaner
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  # Combined tarball for Homebrew
  - id: cache-cleaner
    name_template: "cache-cleaner-{{ .Version }}-darwin-{{ .Arch }}"
    files:
      - none*  # Only include binaries, no extra files

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - 'typo'
  groups:
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance Improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Other Changes'
      order: 999

# Homebrew tap configuration
homebrew_casks:
  - name: cache-cleaner
    # Use the cache-cleaner archive which includes all binaries
    ids:
      - cache-cleaner

    # List all three binaries to install
    binaries:
      - dev-cache
      - git-cleaner
      - mac-cache-cleaner

    repository:
      owner: markcallen
      name: homebrew-cache-cleaner
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Casks
    homepage: https://github.com/markcallen/cache-cleaner
    description: "Collection of Go CLI tools for reclaiming disk space on development machines"

    # Caveats to display after installation
    caveats: |
      cache-cleaner includes three utilities:
        • dev-cache     - Scans for project cache directories
        • git-cleaner   - Finds and optimizes .git directories
        • mac-cache-cleaner - Runs safe cleanup commands for developer tools

      Quick start:
        dev-cache --init
        git-cleaner --scan ~/src
        mac-cache-cleaner --init

      Documentation: https://github.com/markcallen/cache-cleaner

    # Remove quarantine attribute on macOS since binaries are not signed/notarized
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dev-cache"]
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-cleaner"]
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mac-cache-cleaner"]
          end

release:
  github:
    owner: markcallen
    name: cache-cleaner
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Cache Cleaner {{ .Tag }}

    A collection of Go CLI tools for reclaiming disk space on development machines.

    ### Installation

    **Recommended: Homebrew**
    ```bash
    brew tap markcallen/cache-cleaner
    brew install cache-cleaner
    ```

    **Alternative: Direct Download**
    Download the binaries for your architecture below and place them in your PATH.

  footer: |
    **Full Changelog**: https://github.com/markcallen/cache-cleaner/compare/{{ .PreviousTag }}...{{ .Tag }}

  name_template: "{{.ProjectName}}-v{{.Version}}"
